### PR TITLE
Allow specification of static features

### PR DESCRIPTION
**Pull request by kitsonk**
**Type:** feature

This provides functionality that allows static features to be provided in the global
enviornment prior to the `has` module being loaded.  Features asserted in this
fashion will override any environmentaly defined features.

**Related Issue:** #1 

Please review this checklist before submitting your PR:

* [X] There is a related issue
* [X] All contributors have signed a CLA
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] The code passes the CI tests
* [X] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

### CODE REVIEW

**Comment by matt-gadd** [comment]
@kitsonk you should still be able to unit test this no?

**Comment by kitsonk** [comment]
> you should still be able to unit test this no?

It was going to get complicated, with unloading the module, setting the global variable and then reloading the module, all from within the unit tests.  Any thoughts on a way to address that?

**Comment by kitsonk** [comment]
@matt-gadd I took a look at this again... since the AMD doesn't have a formal `undef` API and we don't have anything implemented in `dojo-loader`.  This makes it really challenging to unload/load modules.  The functional tests provide code coverage to all the affected lines.  So given that, my recommendation is we just move forward without specific unit tests.

**Comment by kitsonk** [comment]
ooops... it does have `undef`.  I have converted the functional tests to unit tests.

**Pull request merged**
